name: stayspot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  upi_india: ^3.0.1
  firebase_core: ^2.18.0
  firebase_auth: ^4.12.0
  firebase_auth_web: ^5.12.0
  google_sign_in: ^6.1.5
  font_awesome_flutter: ^10.5.0
  cloud_firestore: ^4.17.5
  image_picker: ^1.1.2
  firebase_storage: ^11.7.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/google-logo.png
    - assets/images/empty_wishlist.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500